# Generated by Django 4.2.5 on 2023-09-19 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='reservation_link',
            field=models.URLField(blank=True, default='', verbose_name='reservation_url'),
        ),
    ]
